[package]
name = "rvc-spec-vectors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Spec vectors + KAT codegen"

[lints]
workspace = true

[dependencies]
serde_yaml.workspace = true
snap.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
