[package]
name = "rvc-gloas"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Gloas progressive SSZ"

[lints]
workspace = true

[dependencies]
libssz.workspace = true
libssz-derive.workspace = true
libssz-merkle.workspace = true
libssz-types.workspace = true
