[package]
name = "rvc-block-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
beacon.workspace = true
crypto.workspace = true
observability.workspace = true
eth-types.workspace = true
hex.workspace = true
metrics.workspace = true
sha2.workspace = true
signer.workspace = true
thiserror.workspace = true
timing.workspace = true
tracing.workspace = true
tree_hash.workspace = true
serde_json.workspace = true
validator-store.workspace = true
rvc-gloas.workspace = true

[dev-dependencies]
crypto.workspace = true
eth-types = { workspace = true, features = ["test-fixtures"] }
rvc-gloas = { workspace = true, features = ["test-fixtures"] }
tokio = { workspace = true, features = ["macros", "rt", "time"] }
toml.workspace = true
tracing-test.workspace = true
