//! Canonical 70 operator-knob names.
//!
//! These are the historical flat / `CliOverrides` names plus the four BN
//! timeouts promoted in ARCH-4j. ARCH-4d's corpus and G-2 clause (iii) use
//! this list after `CliOverrides` is deleted.

/// Every remaining operator knob that had a `CliOverrides` field before
/// ARCH-4i, plus the four BN timeouts promoted to `Config` in ARCH-4j.
///
/// Count is **70**.
pub const OPERATOR_KNOB_NAMES: &[&str] = &[
    "beacon_url",
    "beacon_nodes",
    "keystore_path",
    "password_file",
    "slashing_db_path",
    "init_slashing_db",
    "group_commit_batch_size",
    "group_commit_wait_to_fill_ms",
    "allow_unsupported_fork",
    "metrics_address",
    "metrics_port",
    "network",
    "genesis_time",
    "genesis_validators_root",
    "graffiti",
    "log_level",
    "doppelganger_detection",
    "keymanager_enabled",
    "keymanager_address",
    "keymanager_token_file",
    "remote_signer_url",
    "remote_signer_allowed_hosts",
    "key_decrypt_threads",
    "tracing_endpoint",
    "tracing_exporter",
    "tracing_sample_rate",
    "tracing_max_queue_size",
    "tracing_max_export_batch_size",
    "tracing_service_name",
    "secret_provider",
    "gcp_project_id",
    "gcp_secret_prefix",
    "secret_refresh_interval",
    "secret_provider_strict",
    "allow_insecure_remote_signer",
    "keymanager_cors_origins",
    "keymanager_body_limit",
    "grpc_signer_url",
    "grpc_signer_tls_cert",
    "grpc_signer_tls_key",
    "grpc_signer_tls_ca_cert",
    "disable_attesting",
    "slashed_validators_action",
    "builder_circuit_breaker_consecutive_limit",
    "builder_circuit_breaker_epoch_limit",
    "disable_keystore_locking",
    "proposer_nodes",
    "broadcast",
    "proposer_config_url",
    "proposer_config_file",
    "proposer_config_refresh_interval",
    "proposer_config_url_token",
    "proposer_config_url_insecure",
    "monitoring_endpoint",
    "monitoring_interval",
    "monitoring_endpoint_insecure",
    "logfile",
    "logfile_max_size",
    "logfile_max_number",
    "logfile_compress",
    "logfile_level",
    "block_selection_mode",
    "validator_registration_batch_size",
    "validator_registration_batch_delay",
    "validators_config",
    "beacon_max_body_bytes",
    "block_production_timeout",
    "attestation_timeout",
    "aggregate_timeout",
    "duty_fetch_timeout",
];
