[package]
name = "rvc-grpc-signer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
crypto.workspace = true
observability.workspace = true
eth-types.workspace = true
hex.workspace = true
signer-proto = { workspace = true, features = ["server", "client"] }
tonic = { workspace = true, features = ["transport", "tls"] }
tracing.workspace = true
tree_hash.workspace = true
url.workspace = true
zeroize.workspace = true

[dev-dependencies]
eth-types = { workspace = true, features = ["test-fixtures"] }
hex.workspace = true
prost.workspace = true
tree_hash.workspace = true
rvc-spec-vectors = { workspace = true, features = ["test-fixtures"] }
rvc-test-support.workspace = true
slashing.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream.workspace = true
tracing-subscriber.workspace = true
